version: '3'

tasks:
  default: task --list

  switch:
    cmds:
    - sudo cp configuration.nix /etc/nixos/configuration.nix
    - sudo cp hardware-configuration.nix /etc/nixos/hardware-configuration.nix
    - sudo nixos-rebuild switch