version: '3'

vars:
  HOSTNAME:
    sh: hostname -s
  PWD:
    sh: pwd

tasks:
  default: task --list

  update:
    desc: Updates all Nix flake inputs and updates flake.lock.
    cmds:
    - nix flake update

  # Recent Git update broke `sudo nixos-rebuild`. Instead we now specify `--use-remote-sudo`
  # https://github.com/NixOS/nixpkgs/issues/169193#issuecomment-1113003347
  nixos:
    desc: Compiles and activates new NixOS config.
    cmds:
    - nixos-rebuild switch --use-remote-sudo --flake '.#{{.HOSTNAME}}' {{.CLI_ARGS}}

  nixos:tec:
    desc: Compiles and activates new NixOS config (tec).
    cmds:
    - rsync --recursive --exclude=".git*" --filter="dir-merge,- .gitignore" {{.PWD}}/* nixos@192.168.0.5:~/nix-config
    - ssh nixos@192.168.0.5 "nixos-rebuild switch --use-remote-sudo --flake ~/nix-config#tec {{.CLI_ARGS}}"

  darwin:
    desc: Compiles and activates new macOS config.
    cmds:
    - /run/current-system/sw/bin/darwin-rebuild switch --flake '.#{{.HOSTNAME}}' {{.CLI_ARGS}}

  home:
    desc: Compiles and actives new Home Manager config.
    cmds:
    - home-manager switch --flake '.#{{.HOSTNAME}}' {{.CLI_ARGS}}

  home:devserver:
    desc: Compiles and actives new Home Manager config.
    cmds:
    - sed -i 's|#"vim:meta.nvim"|"vim:meta.nvim"|g' flake.nix
    - home-manager --extra-experimental-features "nix-command flakes" switch --flake '.#devserver' {{.CLI_ARGS}}
    - sed -i 's|[^#]"vim:meta.nvim"| #"vim:meta.nvim"|g' flake.nix

  fmt:
    desc: Formats code in this project.
    cmds:
    - nixpkgs-fmt .

  gc:
    desc: Removes all unused objects from the Nix store.
    cmds:
    - nix-collect-garbage --delete-old
    - sudo nix-collect-garbage --delete-old

  # TODO: Launch with the current flake in scope
  repl:
    desc: Launches a Nix repl with Nixpkgs in scope.
    cmds:
    - nix repl '<nixpkgs>'
