version: '3'

vars:
  HOSTNAME:
    sh: hostname -s

tasks:
  default: task --list

  update:
    desc: Updates all Nix flake inputs and updates flake.lock.
    cmds:
    - nix flake update

  nixos:
    desc: Compiles and activates new NixOS config.
    cmds:
    - sudo nixos-rebuild switch --flake '.#default' {{.CLI_ARGS}}

  darwin:
    desc: Compiles and activates new macOS config.
    cmds:
    - darwin-rebuild switch --flake '.#default' {{.CLI_ARGS}}

  home:
    desc: Compiles and actives new Home Manager config.
    cmds:
    - home-manager switch --flake '.#{{.HOSTNAME}}' {{.CLI_ARGS}}

  fmt:
    desc: Formats code in this project.
    cmds:
    - nixpkgs-fmt .

  gc:
    desc: Removes all unused objects from the Nix store.
    cmds:
    - nix-collect-garbage --delete-old

  # TODO: Launch with the current flake in scope
  repl:
    desc: Launches a Nix repl with Nixpkgs in scope.
    cmds:
    - nix repl '<nixpkgs>'
