version: "3"

env:
  OS:
    sh: uname
  # Trim domain suffix from hostname
  HOSTNAME:
    sh: hostname -s
  # MacOS hostname is flapping, so forcefully set the proper one
  HOSTNAME_HACK: '{{ if eq .OS "Darwin" }}bobbery{{ else }}{{ .HOSTNAME }}{{ end }}'

tasks:
  default: task --list
  hostname: echo $HOSTNAME_HACK

  # Nix -----------------------------------------------------------------------

  nix:install:
    desc: Install Nix
    cmd: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

  nix:uninstall:
    desc: Uninstall Nix
    cmd: /nix/nix-installer uninstall

  # https://docs.determinate.systems/flakehub/faq/#upgrade-nix
  nix:upgrade:
    desc: Upgrade Nix
    cmd: sudo nix upgrade-nix --nix-store-paths-url https://releases.nixos.org/nix/nix-2.18.1/fallback-paths.nix

  nix:update:
    aliases: [ up ]
    desc: Update Nix flake inputs
    cmd: nix flake update

  nix:gc:
    aliases: [ gc ]
    desc: Remove unused objects from the Nix store
    cmds:
    - nix-collect-garbage --delete-old
    - sudo nix-collect-garbage --delete-old

  nix:repl:
    desc: Launch a repl for this Nix flake
    cmds:
    - echo 'To load flake config, type `:lf .#` in the repl'
    - nix repl

  # NixOS ---------------------------------------------------------------------

  nixos:switch:
    desc: Compile and activate NixOS config
    cmd: nixos-rebuid switch --sudo --flake .#$HOSTNAME_HACK

  nixos:switch:tec:
    aliases: [ tec ]
    desc: Compile and activate NixOS config (tec)
    cmds:
    - rsync --recursive --delete --exclude='.git*' --filter='dir-merge,- .gitignore' $PWD/* nixos@tec:~/nix-config
    - ssh nixos@tec 'nixos-rebuild switch --sudo --flake ~/nix-config#tec'

  # Darwin --------------------------------------------------------------------

  darwin:install:
    desc: Install nix-darwin
    cmds:
    - nix build .#darwinConfigurations.$HOSTNAME_HACK.system
    - ./result/sw/bin/darwin-rebuild switch --flake .#$HOSTNAME_HACK

  darwin:switch:
    aliases: [ mac ]
    desc: Compile and activate nix-darwin config
    cmd: sudo /run/current-system/sw/bin/darwin-rebuild switch --flake .#$HOSTNAME_HACK

  # Home ----------------------------------------------------------------------

  home:install:
    desc: Install Home Manager
    cmd: nix run .#homeConfigurations.$HOSTNAME_HACK.activationPackage

  home:switch:
    aliases: [ home ]
    desc: Compile and activate Home Manager config
    cmd: home-manager switch --flake .#$HOSTNAME_HACK
