version: '3'

vars:
  HOSTNAME:
    sh: hostname -s

tasks:
  default: task --list

  update:
    desc: Updates all Nix flake inputs and updates flake.lock.
    cmds:
    - nix flake update

  # Recent Git update broke `sudo nixos-rebuild`. Instead we now specify `--use-remote-sudo` instead
  # https://github.com/NixOS/nixpkgs/issues/169193#issuecomment-1113003347
  nixos:
    desc: Compiles and activates new NixOS config.
    cmds:
    - nixos-rebuild switch --use-remote-sudo --flake '.#bobbery' {{.CLI_ARGS}}

  nixos-tec:
    desc: Compiles and activates new NixOS config.
    cmds:
    - nixos-rebuild switch --use-remote-sudo --flake '.#tec' --build-host nixos@192.168.0.5 --target-host nixos@192.168.0.5 {{.CLI_ARGS}}

  darwin:
    desc: Compiles and activates new macOS config.
    cmds:
    - darwin-rebuild switch --flake '.#default' {{.CLI_ARGS}}

  home:
    desc: Compiles and actives new Home Manager config.
    cmds:
    - home-manager switch --flake '.#{{.HOSTNAME}}' {{.CLI_ARGS}}

  fmt:
    desc: Formats code in this project.
    cmds:
    - nixpkgs-fmt .

  gc:
    desc: Removes all unused objects from the Nix store.
    cmds:
    - sudo nix-collect-garbage --delete-old
    - nix-collect-garbage --delete-old

  # TODO: Launch with the current flake in scope
  repl:
    desc: Launches a Nix repl with Nixpkgs in scope.
    cmds:
    - nix repl '<nixpkgs>'
