version: '3'

tasks:
  default: task --list

  home:
    desc: Updates home config.
    cmds:
    - home-manager switch -f ./home

  nixos:
    desc: Updates NixOS config.
    cmds:
    - sudo cp nixos/configuration.nix /etc/nixos/configuration.nix
    - sudo cp nixos/hardware-configuration.nix /etc/nixos/hardware-configuration.nix
    - sudo nixos-rebuild switch

  macos:
    desc: Updates macOS config.
    cmds:
    - cp macos/darwin-configuration.nix ~/.nixpkgs/darwin-configuration.nix
    - darwin-rebuild switch
