version: '3'

tasks:
  default: task --list

  update:
    desc: Updates all Nix channels (ie, pull latest derivation versions).
    cmds:
    - nix-channel --update

  nixos:
    desc: Compiles and activates new NixOS config.
    cmds:
    - sudo cp nixos/configuration.nix /etc/nixos/configuration.nix
    - sudo cp nixos/hardware-configuration.nix /etc/nixos/hardware-configuration.nix
    - sudo nixos-rebuild switch

  darwin:
    desc: Compiles and activates new macOS config.
    cmds:
    - cp darwin/default.nix ~/.nixpkgs/darwin-configuration.nix
    - darwin-rebuild switch

  darwin:flake:
    desc: Compiles and activates new macOS config using Nix flakes (BROKEN).
    cmds:
    - darwin-rebuild switch --flake '.#default'

  home:
    desc: Compiles and actives new Home Manager config.
    cmds:
    - home-manager switch --flake '.#default'

  fmt:
    desc: Formats code in this project.
    cmds:
    - nixpkgs-fmt .
