version: '3'

tasks:
  default: task --list

  update:
    desc: Updates all Nix channels (ie, pull latest derivation versions).
    cmds:
    - nix-channel --update

  nixos:
    desc: Compiles and activates new NixOS config.
    cmds:
    - sudo nixos-rebuild switch --flake '.#default'

  darwin:
    desc: Compiles and activates new macOS config.
    cmds:
    - darwin-rebuild switch --flake '.#default'

  home:
    desc: Compiles and actives new Home Manager config.
    cmds:
    - home-manager switch --flake '.#default'

  fmt:
    desc: Formats code in this project.
    cmds:
    - nixpkgs-fmt .
