version: '3'

tasks:
  default: task --list

  update:
    desc: Updates all Nix channels (ie, pull latest derivation versions).
    cmds:
    - nix-channel --update

  home:
    desc: Compiles and actives new Home Manager config.
    cmds:
    - home-manager switch -f ./home

  nixos:
    desc: Compiles and activates new NixOS config.
    cmds:
    - sudo cp nixos/configuration.nix /etc/nixos/configuration.nix
    - sudo cp nixos/hardware-configuration.nix /etc/nixos/hardware-configuration.nix
    - sudo nixos-rebuild switch

  macos:
    desc: Compiles and activates new macOS config.
    cmds:
    - cp macos/default.nix ~/.nixpkgs/darwin-configuration.nix
    - darwin-rebuild switch

  fmt:
    desc: Formats code in this project.
    cmds:
    - nixpkgs-fmt .
